// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcVgXGBcWuGwofXeEwESSwsFuQkd_SjA',
    appId: '1:878493929047:web:0cd5389fdff05e495c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    authDomain: 'mathdictionary-f4765.firebaseapp.com',
    storageBucket: 'mathdictionary-f4765.appspot.com',
    measurementId: 'G-PP1N3C901P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmokmqYseqMFUy-_F5C0z3gcZ35oEZ8I',
    appId: '1:878493929047:android:0760eab3968c50965c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    storageBucket: 'mathdictionary-f4765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkiqRWNq3ZHWS-Do8XN-eIzYv1jaO9CoQ',
    appId: '1:878493929047:ios:371638537afc6aac5c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    storageBucket: 'mathdictionary-f4765.appspot.com',
    iosBundleId: 'com.example.dictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkiqRWNq3ZHWS-Do8XN-eIzYv1jaO9CoQ',
    appId: '1:878493929047:ios:371638537afc6aac5c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    storageBucket: 'mathdictionary-f4765.appspot.com',
    iosBundleId: 'com.example.dictionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGcVgXGBcWuGwofXeEwESSwsFuQkd_SjA',
    appId: '1:878493929047:web:999845088669071e5c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    authDomain: 'mathdictionary-f4765.firebaseapp.com',
    storageBucket: 'mathdictionary-f4765.appspot.com',
    measurementId: 'G-R7BQZS5LFC',
  );

}